import { apiClient } from '../../../services/apiClient';

export const administrationService = {
  overview: () => apiClient<Record<string, unknown>>('/admin/overview'),
  configurations: () => apiClient<Array<Record<string, unknown>>>('/admin/configurations'),
  configuration: (key: string) => apiClient<Record<string, unknown>>(`/admin/configurations/${key}`),
  configurationVersions: (key: string) => apiClient<Array<Record<string, unknown>>>(`/admin/configurations/${key}/versions`),
  configurationHistory: (key: string) => apiClient<Array<Record<string, unknown>>>(`/admin/configurations/${key}/history`),
  configurationPublish: (key: string) => apiClient<Record<string, unknown>>(`/admin/configurations/${key}/publish`),
  configurationRollback: (key: string) => apiClient<Record<string, unknown>>(`/admin/configurations/${key}/rollback`),
  refreshConfigurationCache: (key: string) => apiClient<Record<string, unknown>>(`/admin/configurations/${key}/refresh-cache`, { method: 'POST' }),
  updateConfiguration: (key: string, payload: { enabled?: boolean; values?: Record<string, unknown>; reason?: string; change_summary?: string }) => apiClient<Record<string, unknown>>(`/admin/configurations/${key}`, { method: 'PUT', body: JSON.stringify(payload) }),
  modules: () => apiClient<Array<Record<string, unknown>>>('/admin/modules'),
  features: () => apiClient<Array<Record<string, unknown>>>('/admin/features'),
  updateFeature: (feature: string, state: 'enabled' | 'disabled' | 'hidden') => apiClient<Record<string, unknown>>(`/admin/features/${feature}`, { method: 'PUT', body: JSON.stringify({ state }) }),
  health: () => apiClient<Record<string, unknown>>('/admin/health'),
  healthScore: () => apiClient<Record<string, unknown>>('/admin/health-score'),
  security: () => apiClient<Record<string, unknown>>('/admin/security'),
  monitoring: () => apiClient<Record<string, unknown>>('/admin/monitoring'),
  monitoringSummary: () => apiClient<Record<string, unknown>>('/admin/monitoring/summary'),
  performance: () => apiClient<Record<string, unknown>>('/admin/monitoring/performance'),
  capacity: () => apiClient<Record<string, unknown>>('/admin/monitoring/capacity'),
  alerts: () => apiClient<Record<string, unknown>>('/admin/monitoring/alerts'),
  audit: () => apiClient<Record<string, unknown>>('/admin/audit'),
  auditCenter: () => apiClient<Record<string, unknown>>('/admin/audit/center'),
  operationalDashboard: () => apiClient<Record<string, unknown>>('/admin/operational-dashboard'),
  backup: () => apiClient<Record<string, unknown>>('/admin/backup'),
  integration: () => apiClient<Record<string, unknown>>('/admin/integration'),
};
