import { useMemo, useState } from 'react';
import { Activity, Archive, Database, FolderCog, Gauge, KeyRound, RefreshCw, ShieldCheck, SlidersHorizontal, Users } from 'lucide-react';
import { Breadcrumb } from '../components/Breadcrumb';
import { useAdministrationAudit, useAdministrationBackup, useAdministrationConfigurations, useAdministrationFeatures, useAdministrationHealth, useAdministrationIntegration, useAdministrationModules, useAdministrationMonitoring, useAdministrationOverview, useAdministrationSecurity, useUpdateConfiguration, useUpdateFeature } from '../features/administration/hooks/useAdministration';

const sections = ['Dashboard', 'Users', 'Roles', 'Permissions', 'Configuration', 'Security', 'Monitoring', 'Audit', 'Backup', 'Integration', 'System Health'] as const;
type Section = typeof sections[number];
const icons = [Gauge, Users, ShieldCheck, KeyRound, FolderCog, ShieldCheck, Activity, Archive, Database, SlidersHorizontal, Activity];

export function AdministrationPage() {
  const [section, setSection] = useState<Section>('Dashboard');
  const [search, setSearch] = useState('');
  const [message, setMessage] = useState('Administration workspace ready.');
  const overview = useAdministrationOverview(); const configurations = useAdministrationConfigurations(); const modules = useAdministrationModules(); const features = useAdministrationFeatures(); const health = useAdministrationHealth(); const security = useAdministrationSecurity(); const monitoring = useAdministrationMonitoring(); const audit = useAdministrationAudit(); const backup = useAdministrationBackup(); const integration = useAdministrationIntegration();
  const updateConfiguration = useUpdateConfiguration(); const updateFeature = useUpdateFeature();
  const featureCount = features.data?.data.length ?? 0;
  const selected = useMemo(() => ({ Dashboard: overview.data?.data, Configuration: configurations.data?.data, Security: security.data?.data, Monitoring: monitoring.data?.data, Audit: audit.data?.data, Backup: backup.data?.data, Integration: integration.data?.data, 'System Health': health.data?.data, Users: modules.data?.data, Roles: modules.data?.data, Permissions: modules.data?.data }[section]), [section, overview.data, configurations.data, security.data, monitoring.data, audit.data, backup.data, integration.data, health.data, modules.data]);
  const loading = overview.isLoading || health.isLoading;
  const error = overview.isError && health.isError;
  const cards = Object.entries((overview.data?.data.platform_summary ?? {}) as Record<string, unknown>);
  const filtered = Array.isArray(selected) ? selected.filter((item) => JSON.stringify(item).toLowerCase().includes(search.toLowerCase())) : selected;
  function refresh() { void overview.refetch(); void health.refetch(); void monitoring.refetch(); setMessage('Administration workspace refreshed.'); }
  return <div className="space-y-5">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><Breadcrumb items={['UtiFarm', 'System Administration']} /><h1 className="mt-2 text-2xl font-semibold text-slate-950 dark:text-slate-50">Administration Control Center</h1><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">Platform metadata, configuration, security, and system readiness workspace.</p></div><button aria-label="Refresh administration workspace" className="inline-flex items-center gap-2 self-start rounded-md bg-brand px-3 py-2 text-sm font-semibold text-white focus:outline-none focus:ring-2 focus:ring-brand focus:ring-offset-2" onClick={refresh} type="button"><RefreshCw aria-hidden="true" className="h-4 w-4" />Refresh</button></div>
    <div className="grid gap-4 xl:grid-cols-[210px_minmax(0,1fr)_280px]"><aside aria-label="Administration navigation" className="rounded-md border border-slate-200 bg-white p-2 dark:border-slate-800 dark:bg-slate-900"><nav className="grid gap-1 sm:grid-cols-2 xl:grid-cols-1">{sections.map((item, index) => { const Icon = icons[index]; return <button aria-current={section === item ? 'page' : undefined} className={section === item ? 'flex items-center gap-2 rounded-md bg-brand-soft px-3 py-2 text-left text-sm font-semibold text-brand-dark focus:outline-none focus:ring-2 focus:ring-brand' : 'flex items-center gap-2 rounded-md px-3 py-2 text-left text-sm text-slate-700 hover:bg-slate-100 focus:outline-none focus:ring-2 focus:ring-brand dark:text-slate-200 dark:hover:bg-slate-800'} key={item} onClick={() => setSection(item)} type="button"><Icon aria-hidden="true" className="h-4 w-4" />{item}</button>; })}</nav></aside>
      <section className="min-w-0 rounded-md border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold text-slate-900 dark:text-white">{section}</h2><p className="text-sm text-slate-500 dark:text-slate-400">Read-only platform data with supported metadata actions.</p></div><input aria-label="Search administration records" className="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand dark:border-slate-700 dark:bg-slate-950" onChange={(event) => setSearch(event.target.value)} placeholder="Search metadata" type="search" value={search} /></div>
        {loading ? <div className="grid gap-3 sm:grid-cols-2"><div className="h-24 animate-pulse rounded-md bg-slate-100 dark:bg-slate-800" /><div className="h-24 animate-pulse rounded-md bg-slate-100 dark:bg-slate-800" /></div> : null}{error ? <p className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700">Administration data could not be loaded. Use refresh to retry.</p> : null}
        {section === 'Dashboard' ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([key, value]) => <article className="rounded-md border border-slate-200 p-4 dark:border-slate-800" key={key}><p className="text-xs font-medium uppercase text-slate-500">{key.replace(/_/g, ' ')}</p><p className="mt-2 text-2xl font-semibold text-slate-900 dark:text-white">{String(value)}</p></article>)}</div> : null}
        {Array.isArray(filtered) ? <div className="space-y-2">{filtered.length === 0 ? <p className="rounded-md border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">No Data Available</p> : filtered.map((item, index) => <pre className="overflow-auto rounded-md border border-slate-200 bg-slate-50 p-3 text-xs text-slate-700 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300" key={index}>{JSON.stringify(item, null, 2)}</pre>)}</div> : <pre className="overflow-auto rounded-md border border-slate-200 bg-slate-50 p-3 text-xs text-slate-700 dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300">{JSON.stringify(filtered ?? {}, null, 2)}</pre>}
      </section>
      <aside className="rounded-md border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-sm font-semibold text-slate-900 dark:text-white">Controls</h2><p aria-live="polite" className="mt-2 text-sm text-slate-500 dark:text-slate-400">{message}</p><p className="mt-2 text-xs text-slate-500">{featureCount} registered feature toggles</p><div className="mt-4 space-y-3"><button className="w-full rounded-md border border-slate-200 px-3 py-2 text-left text-sm font-medium hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-brand dark:border-slate-700 dark:hover:bg-slate-800" onClick={() => { if (window.confirm('Disable security metadata configuration?')) updateConfiguration.mutate({ key: 'security', enabled: false }, { onSuccess: () => setMessage('Security configuration updated.'), onError: (e) => setMessage(e.message) }); }} type="button">Toggle security configuration</button><button className="w-full rounded-md border border-slate-200 px-3 py-2 text-left text-sm font-medium hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-brand dark:border-slate-700 dark:hover:bg-slate-800" onClick={() => updateFeature.mutate({ feature: 'monitoring', state: 'enabled' }, { onSuccess: () => setMessage('Monitoring feature enabled.'), onError: (e) => setMessage(e.message) })} type="button">Enable monitoring feature</button><p className="text-xs text-slate-500">User, role, and permission management use the existing APIs; this workspace exposes their available module metadata until dedicated UI contracts are enabled.</p></div></aside></div>
    <footer className="rounded-md border border-slate-200 bg-white px-4 py-3 text-xs text-slate-500 dark:border-slate-800 dark:bg-slate-900">Status refreshes every 60 seconds for monitoring and health. Backend authorization remains the source of truth.</footer>
  </div>;
}
