import type { MasterDataFieldConfig, MasterDataResourceConfig, MasterDataResourceKey } from '../types/masterData';

const descriptionField: MasterDataFieldConfig = {
  key: 'description',
  label: 'Description',
  type: 'textarea',
  gridSpan: 'full',
};

const locationFields: MasterDataFieldConfig[] = [
  { key: 'province_id', label: 'Province', type: 'select', lookupResource: 'provinces', lookupLabelKey: 'province_name' },
  { key: 'city_id', label: 'City', type: 'select', lookupResource: 'cities', lookupLabelKey: 'city_name' },
  { key: 'district_id', label: 'District', type: 'select', lookupResource: 'districts', lookupLabelKey: 'district_name' },
  { key: 'village_id', label: 'Village', type: 'select', lookupResource: 'villages', lookupLabelKey: 'village_name' },
  { key: 'postal_code', label: 'Postal Code' },
];

export const masterDataResources: MasterDataResourceConfig[] = [
  {
    key: 'companies',
    label: 'Companies',
    description: 'Company profiles used by farm operations.',
    group: 'Organization',
    codeKey: 'company_code',
    nameKey: 'company_name',
    columns: [
      { key: 'company_code', label: 'Code' },
      { key: 'company_name', label: 'Company' },
      { key: 'email', label: 'Email' },
      { key: 'province_id', label: 'Province', lookupResource: 'provinces', lookupLabelKey: 'province_name' },
      { key: 'is_active', label: 'Active' },
    ],
    fields: [
      { key: 'company_code', label: 'Company Code', required: true },
      { key: 'company_name', label: 'Company Name', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone' },
      { key: 'website', label: 'Website', type: 'url' },
      { key: 'tax_number', label: 'Tax Number' },
      { key: 'address', label: 'Address', type: 'textarea', gridSpan: 'full' },
      ...locationFields,
    ],
  },
  {
    key: 'farms',
    label: 'Farms',
    description: 'Farm units connected to company ownership.',
    group: 'Organization',
    codeKey: 'farm_code',
    nameKey: 'farm_name',
    columns: [
      { key: 'farm_code', label: 'Code' },
      { key: 'farm_name', label: 'Farm' },
      { key: 'company_id', label: 'Company', lookupResource: 'companies', lookupLabelKey: 'company_name' },
      { key: 'is_active', label: 'Active' },
    ],
    fields: [
      { key: 'company_id', label: 'Company', type: 'select', required: true, lookupResource: 'companies', lookupLabelKey: 'company_name' },
      { key: 'farm_code', label: 'Farm Code', required: true },
      { key: 'farm_name', label: 'Farm Name', required: true },
      { key: 'latitude', label: 'Latitude', type: 'number' },
      { key: 'longitude', label: 'Longitude', type: 'number' },
      descriptionField,
    ],
  },
  {
    key: 'pond-areas',
    label: 'Pond Areas',
    description: 'Operational pond area grouping inside farms.',
    group: 'Production',
    codeKey: 'pond_area_code',
    nameKey: 'pond_area_name',
    columns: [
      { key: 'pond_area_code', label: 'Code' },
      { key: 'pond_area_name', label: 'Pond Area' },
      { key: 'farm_id', label: 'Farm', lookupResource: 'farms', lookupLabelKey: 'farm_name' },
      { key: 'total_area', label: 'Total Area' },
    ],
    fields: [
      { key: 'farm_id', label: 'Farm', type: 'select', required: true, lookupResource: 'farms', lookupLabelKey: 'farm_name' },
      { key: 'pond_area_code', label: 'Pond Area Code', required: true },
      { key: 'pond_area_name', label: 'Pond Area Name', required: true },
      { key: 'area_size', label: 'Area Size', type: 'number' },
      descriptionField,
    ],
  },
  {
    key: 'ponds',
    label: 'Ponds',
    description: 'Pond master list used by culture operations.',
    group: 'Production',
    codeKey: 'pond_code',
    nameKey: 'pond_name',
    columns: [
      { key: 'pond_code', label: 'Code' },
      { key: 'pond_name', label: 'Pond' },
      { key: 'pond_area_id', label: 'Pond Area', lookupResource: 'pond-areas', lookupLabelKey: 'pond_area_name' },
      { key: 'depth', label: 'Depth' },
      { key: 'is_active', label: 'Active' },
    ],
    fields: [
      { key: 'pond_area_id', label: 'Pond Area', type: 'select', required: true, lookupResource: 'pond-areas', lookupLabelKey: 'pond_area_name' },
      { key: 'pond_code', label: 'Pond Code', required: true },
      { key: 'pond_name', label: 'Pond Name', required: true },
      { key: 'depth', label: 'Depth', type: 'number' },
      { key: 'area_size', label: 'Area Size', type: 'number' },
      { key: 'volume', label: 'Volume', type: 'number' },
      descriptionField,
    ],
  },
  {
    key: 'fish-species',
    label: 'Fish Species',
    description: 'Species reference data for stocking and harvest.',
    group: 'Production',
    codeKey: 'fish_species_code',
    nameKey: 'fish_species_name',
    columns: [
      { key: 'fish_species_code', label: 'Code' },
      { key: 'fish_species_name', label: 'Species' },
      { key: 'scientific_name', label: 'Scientific Name' },
    ],
    fields: [
      { key: 'fish_species_code', label: 'Species Code', required: true },
      { key: 'fish_species_name', label: 'Species Name', required: true },
      { key: 'scientific_name', label: 'Scientific Name' },
      descriptionField,
    ],
  },
  {
    key: 'fish-strains',
    label: 'Fish Strains',
    description: 'Strain reference data attached to fish species.',
    group: 'Production',
    codeKey: 'fish_strain_code',
    nameKey: 'fish_strain_name',
    columns: [
      { key: 'fish_strain_code', label: 'Code' },
      { key: 'fish_strain_name', label: 'Strain' },
      { key: 'fish_species_id', label: 'Species', lookupResource: 'fish-species', lookupLabelKey: 'fish_species_name' },
      { key: 'is_active', label: 'Active' },
    ],
    fields: [
      { key: 'fish_species_id', label: 'Fish Species', type: 'select', required: true, lookupResource: 'fish-species', lookupLabelKey: 'fish_species_name' },
      { key: 'fish_strain_code', label: 'Strain Code', required: true },
      { key: 'fish_strain_name', label: 'Strain Name', required: true },
      descriptionField,
    ],
  },
  {
    key: 'feed-brands',
    label: 'Feed Brands',
    description: 'Feed producer and brand reference data.',
    group: 'Feed',
    codeKey: 'feed_brand_code',
    nameKey: 'feed_brand_name',
    columns: [
      { key: 'feed_brand_code', label: 'Code' },
      { key: 'feed_brand_name', label: 'Brand' },
    ],
    fields: [
      { key: 'feed_brand_code', label: 'Brand Code', required: true },
      { key: 'feed_brand_name', label: 'Brand Name', required: true },
      descriptionField,
    ],
  },
  {
    key: 'feed-categories',
    label: 'Feed Categories',
    description: 'Feed category reference data.',
    group: 'Feed',
    codeKey: 'feed_category_code',
    nameKey: 'feed_category_name',
    columns: [
      { key: 'feed_category_code', label: 'Code' },
      { key: 'feed_category_name', label: 'Category' },
    ],
    fields: [
      { key: 'feed_category_code', label: 'Category Code', required: true },
      { key: 'feed_category_name', label: 'Category Name', required: true },
      descriptionField,
    ],
  },
  {
    key: 'feed-types',
    label: 'Feed Types',
    description: 'Feed type catalog connected to brand and category.',
    group: 'Feed',
    codeKey: 'feed_type_code',
    nameKey: 'feed_type_name',
    columns: [
      { key: 'feed_type_code', label: 'Code' },
      { key: 'feed_type_name', label: 'Feed Type' },
      { key: 'feed_brand_id', label: 'Brand', lookupResource: 'feed-brands', lookupLabelKey: 'feed_brand_name' },
      { key: 'feed_category_id', label: 'Category', lookupResource: 'feed-categories', lookupLabelKey: 'feed_category_name' },
    ],
    fields: [
      { key: 'feed_brand_id', label: 'Feed Brand', type: 'select', required: true, lookupResource: 'feed-brands', lookupLabelKey: 'feed_brand_name' },
      { key: 'feed_category_id', label: 'Feed Category', type: 'select', required: true, lookupResource: 'feed-categories', lookupLabelKey: 'feed_category_name' },
      { key: 'feed_type_code', label: 'Feed Type Code', required: true },
      { key: 'feed_type_name', label: 'Feed Type Name', required: true },
      { key: 'protein_content', label: 'Protein Content (%)', type: 'number' },
      { key: 'fat_content', label: 'Fat Content (%)', type: 'number' },
      { key: 'fiber_content', label: 'Fiber Content (%)', type: 'number' },
      { key: 'moisture', label: 'Moisture (%)', type: 'number' },
      { key: 'ash_content', label: 'Ash Content (%)', type: 'number' },
      { key: 'pellet_size', label: 'Pellet Size', type: 'number' },
      { key: 'packaging_size', label: 'Packaging Size', type: 'number' },
      { key: 'packaging_unit_id', label: 'Packaging Unit', type: 'select', lookupResource: 'units', lookupLabelKey: 'unit_name' },
      descriptionField,
    ],
  },
  {
    key: 'units',
    label: 'Units',
    description: 'Measurement units used across operations.',
    group: 'Reference',
    codeKey: 'unit_code',
    nameKey: 'unit_name',
    columns: [
      { key: 'unit_code', label: 'Code' },
      { key: 'unit_name', label: 'Unit' },
      { key: 'symbol', label: 'Symbol' },
    ],
    fields: [
      { key: 'unit_code', label: 'Unit Code', required: true },
      { key: 'unit_name', label: 'Unit Name', required: true },
      { key: 'symbol', label: 'Symbol' },
    ],
  },
  {
    key: 'suppliers',
    label: 'Suppliers',
    description: 'Supplier contacts and operating references.',
    group: 'Organization',
    codeKey: 'supplier_code',
    nameKey: 'supplier_name',
    columns: [
      { key: 'supplier_code', label: 'Code' },
      { key: 'supplier_name', label: 'Supplier' },
      { key: 'supplier_type', label: 'Type' },
      { key: 'phone', label: 'Phone' },
      { key: 'is_active', label: 'Active' },
    ],
    fields: [
      { key: 'supplier_code', label: 'Supplier Code', required: true },
      { key: 'supplier_name', label: 'Supplier Name', required: true },
      { key: 'supplier_type', label: 'Supplier Type' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone' },
      { key: 'website', label: 'Website' },
      { key: 'tax_number', label: 'Tax Number' },
      { key: 'address', label: 'Address', type: 'textarea', gridSpan: 'full' },
      ...locationFields,
      { key: 'contact_person', label: 'Contact Person' },
      { key: 'contact_phone', label: 'Contact Phone' },
      { key: 'payment_terms', label: 'Payment Terms' },
      { key: 'credit_limit', label: 'Credit Limit', type: 'number' },
    ],
  },
  {
    key: 'provinces',
    label: 'Provinces',
    description: 'Province reference data for location hierarchy.',
    group: 'Reference',
    codeKey: 'province_code',
    nameKey: 'province_name',
    columns: [
      { key: 'province_code', label: 'Code' },
      { key: 'province_name', label: 'Province' },
    ],
    fields: [
      { key: 'province_code', label: 'Province Code', required: true },
      { key: 'province_name', label: 'Province Name', required: true },
      descriptionField,
    ],
  },
  {
    key: 'cities',
    label: 'Cities',
    description: 'City reference data linked to province.',
    group: 'Reference',
    codeKey: 'city_code',
    nameKey: 'city_name',
    columns: [
      { key: 'city_code', label: 'Code' },
      { key: 'city_name', label: 'City' },
      { key: 'province_id', label: 'Province', lookupResource: 'provinces', lookupLabelKey: 'province_name' },
    ],
    fields: [
      { key: 'province_id', label: 'Province', type: 'select', required: true, lookupResource: 'provinces', lookupLabelKey: 'province_name' },
      { key: 'city_code', label: 'City Code', required: true },
      { key: 'city_name', label: 'City Name', required: true },
      descriptionField,
    ],
  },
  {
    key: 'districts',
    label: 'Districts',
    description: 'District reference data linked to city.',
    group: 'Reference',
    codeKey: 'district_code',
    nameKey: 'district_name',
    columns: [
      { key: 'district_code', label: 'Code' },
      { key: 'district_name', label: 'District' },
      { key: 'city_id', label: 'City', lookupResource: 'cities', lookupLabelKey: 'city_name' },
    ],
    fields: [
      { key: 'city_id', label: 'City', type: 'select', required: true, lookupResource: 'cities', lookupLabelKey: 'city_name' },
      { key: 'district_code', label: 'District Code', required: true },
      { key: 'district_name', label: 'District Name', required: true },
      descriptionField,
    ],
  },
  {
    key: 'villages',
    label: 'Villages',
    description: 'Village reference data linked to district.',
    group: 'Reference',
    codeKey: 'village_code',
    nameKey: 'village_name',
    columns: [
      { key: 'village_code', label: 'Code' },
      { key: 'village_name', label: 'Village' },
      { key: 'district_id', label: 'District', lookupResource: 'districts', lookupLabelKey: 'district_name' },
    ],
    fields: [
      { key: 'district_id', label: 'District', type: 'select', required: true, lookupResource: 'districts', lookupLabelKey: 'district_name' },
      { key: 'village_code', label: 'Village Code', required: true },
      { key: 'village_name', label: 'Village Name', required: true },
      descriptionField,
    ],
  },
];

export const masterDataResourceMap = new Map<MasterDataResourceKey, MasterDataResourceConfig>(
  masterDataResources.map((resource) => [resource.key, resource]),
);

export function getMasterDataResource(key: MasterDataResourceKey): MasterDataResourceConfig {
  const resource = masterDataResourceMap.get(key);

  if (!resource) {
    throw new Error(`Unknown master data resource: ${key}`);
  }

  return resource;
}
